import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

const readDescription = "Reads stored Business Autopilot metadata only. It does not send, post, comment, submit forms, call AI, browse, buy ads, execute browser actions, or mutate external systems.";
const writeDescription = "Confirm-saves Business Autopilot internal metadata only. It does not send, post, comment, submit forms, call AI, browse, buy ads, execute browser actions, or mutate external systems.";

export const businessAutopilotRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "business_organizations",
    method: "GET",
    path: "/admin/business/organizations?limit=25",
    label: "Business organizations",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_signals",
    method: "GET",
    path: "/admin/business/signals?limit=25",
    label: "Business signals",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_opportunities",
    method: "GET",
    path: "/admin/business/opportunities?limit=25",
    label: "Business opportunities",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_service_matches",
    method: "GET",
    path: "/admin/business/service-matches?limit=25",
    label: "Business service matches",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_action_drafts",
    method: "GET",
    path: "/admin/business/action-drafts?limit=25",
    label: "Business action drafts",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_approval_requests",
    method: "GET",
    path: "/admin/business/approval-requests?limit=25",
    label: "Business approval requests",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_suppression_list",
    method: "GET",
    path: "/admin/business/suppression?limit=25",
    label: "Business suppression list",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_content_ideas",
    method: "GET",
    path: "/admin/business/content-ideas?limit=25",
    label: "Business content ideas",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_followups",
    method: "GET",
    path: "/admin/business/followups?limit=25",
    label: "Business followups",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_learning_events",
    method: "GET",
    path: "/admin/business/learning?limit=25",
    label: "Business learning events",
    section: "business_autopilot",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: readDescription,
  }),
  route({
    id: "business_organization_save",
    method: "POST",
    path: "/admin/business/organizations?confirm=1",
    label: "Save business organization",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_organizations"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_signal_save",
    method: "POST",
    path: "/admin/business/signals?confirm=1",
    label: "Save business signal",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_signals"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_opportunity_save",
    method: "POST",
    path: "/admin/business/opportunities?confirm=1",
    label: "Save business opportunity",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_opportunities"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_action_draft_save",
    method: "POST",
    path: "/admin/business/action-drafts?confirm=1",
    label: "Save business action draft",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_action_drafts"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_approval_request_save",
    method: "POST",
    path: "/admin/business/approval-requests?confirm=1",
    label: "Save business approval request",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_approval_requests"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_suppression_save",
    method: "POST",
    path: "/admin/business/suppression?confirm=1",
    label: "Save business suppression",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_suppression_list"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_content_idea_save",
    method: "POST",
    path: "/admin/business/content-ideas?confirm=1",
    label: "Save business content idea",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_content_ideas"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_followup_save",
    method: "POST",
    path: "/admin/business/followups?confirm=1",
    label: "Save business followup",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_followups"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
  route({
    id: "business_learning_event_save",
    method: "POST",
    path: "/admin/business/learning?confirm=1",
    label: "Save business learning event",
    section: "business_autopilot",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["business_learning_events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: writeDescription,
  }),
];

export const businessAutopilotReadRouteIds = businessAutopilotRouteCatalogue
  .filter((item) => item.readOnly)
  .map((item) => item.id);

export const businessAutopilotConfirmRouteIds = businessAutopilotRouteCatalogue
  .filter((item) => item.requiresConfirm)
  .map((item) => item.id);
