import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const growthAutonomousDiscoveryRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "growth_research_runs",
    method: "GET",
    path: "/admin/growth/discovery/research-runs?limit=25",
    label: "Growth research runs",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists zero-source autonomous discovery research runs. This is stored internal metadata only and does not crawl, send, post, submit forms, or call AI.",
  }),
  route({
    id: "growth_source_candidates",
    method: "GET",
    path: "/admin/growth/discovery/source-candidates?limit=50",
    label: "Growth source candidates",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists discovered or planned source candidates with crawl policy status, scores, and risk flags. It reads stored records only.",
  }),
  route({
    id: "growth_extracted_signals",
    method: "GET",
    path: "/admin/growth/discovery/signals?limit=50",
    label: "Growth extracted signals",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists stored evidence signals extracted from approved research records. Crawled content is treated as evidence, not instructions.",
  }),
  route({
    id: "growth_opportunity_scores",
    method: "GET",
    path: "/admin/growth/discovery/opportunity-scores?limit=50",
    label: "Growth opportunity scores",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists stored opportunity scores and evidence quality scores for candidate sources. It does not contact prospects or mutate external systems.",
  }),
  route({
    id: "growth_agent_decisions",
    method: "GET",
    path: "/admin/growth/discovery/agent-decisions?limit=50",
    label: "Growth agent decisions",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists internal autonomous discovery decisions such as research_more, reject_candidate, score_candidate, and prepare_approval_pack.",
  }),
  route({
    id: "growth_discovery_feedback",
    method: "GET",
    path: "/admin/growth/discovery/feedback?limit=50",
    label: "Growth discovery feedback",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists operator feedback used to improve future source discovery scoring. It is stored learning metadata only.",
  }),
  route({
    id: "growth_research_run_plan",
    method: "POST",
    path: "/admin/growth/discovery/research-runs/plan?confirm=1",
    label: "Plan Growth research run",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_research_runs"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirm-saves one zero-source research plan as internal metadata only. It does not fetch pages, crawl, send, post, submit forms, or call AI.",
  }),
  route({
    id: "growth_source_candidate_save",
    method: "POST",
    path: "/admin/growth/discovery/source-candidates?confirm=1",
    label: "Save Growth source candidate",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_source_candidates"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirm-saves one candidate source record. It records metadata and risk flags only; it does not crawl the candidate.",
  }),
  route({
    id: "growth_fetch_queue_enqueue",
    method: "POST",
    path: "/admin/growth/discovery/fetch-queue?confirm=1",
    label: "Queue Growth fetch work",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_fetch_queue"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: false,
    description: "Confirm-enqueues bounded future fetch work as internal metadata only. This route itself does not call the network and must not be browser-proxied.",
  }),
  route({
    id: "growth_agent_decision_record",
    method: "POST",
    path: "/admin/growth/discovery/agent-decisions?confirm=1",
    label: "Record Growth agent decision",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_agent_decisions"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirm-records one internal discovery decision with evidence, blocked actions, next internal step, and confidence.",
  }),
  route({
    id: "growth_discovery_feedback_save",
    method: "POST",
    path: "/admin/growth/discovery/feedback?confirm=1",
    label: "Save Growth discovery feedback",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_discovery_feedback"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirm-saves operator feedback for discovery learning. It is internal learning metadata only.",
  }),
];

export const growthAutonomousDiscoveryReadRouteIds = growthAutonomousDiscoveryRouteCatalogue
  .filter((item) => item.readOnly)
  .map((item) => item.id);

export const growthAutonomousDiscoveryConfirmRouteIds = growthAutonomousDiscoveryRouteCatalogue
  .filter((item) => item.requiresConfirm)
  .map((item) => item.id);
