import { Env, getAdminToken } from "../db";

type JsonResponse = (data: any, init?: ResponseInit) => Response;

type RouteSafety = "read_only" | "confirm_required" | "settings_gated" | "public_read_only";

type RouteCatalogueItem = {
  id: string;
  method: string;
  path: string;
  label: string;
  section: "cockpit" | "planner" | "sources" | "drafts" | "safety" | "public";
  safety: RouteSafety;
  readOnly: boolean;
  requiresConfirm: boolean;
  writesTables: string[];
  callsNetwork: boolean;
  callsAI: boolean;
  canSendEmail: boolean;
  costRisk: "none" | "low" | "medium" | "high";
  operatorFacing: boolean;
  operationsHubRecommended: boolean;
  description: string;
};

function authorized(request: Request, env: Env): boolean {
  const token = getAdminToken(env);
  return Boolean(token && (request.headers.get("authorization") || "") === `Bearer ${token}`);
}

const routes: RouteCatalogueItem[] = [
  {
    id: "planner_report",
    method: "GET",
    path: "/admin/planner",
    label: "Planner report",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Full planner state, safe actions, blocked actions, samples, and recommended next action.",
  },
  {
    id: "planner_dashboard",
    method: "GET",
    path: "/admin/planner/dashboard?compact=1",
    label: "Planner dashboard",
    section: "cockpit",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Compact cockpit payload with risk, badges, checklist, counts, latest audit summaries, and refresh hints.",
  },
  {
    id: "planner_dashboard_full",
    method: "GET",
    path: "/admin/planner/dashboard",
    label: "Planner dashboard full",
    section: "cockpit",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: false,
    description: "Full cockpit payload including recent events and source runs for deeper investigation.",
  },
  {
    id: "planner_dashboard_self_test",
    method: "GET",
    path: "/admin/planner/dashboard/self-test?compact=1",
    label: "Dashboard self-test",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Validates the live dashboard contract for UI readiness without writing anything.",
  },
  {
    id: "planner_record",
    method: "POST",
    path: "/admin/planner/record",
    label: "Record planner snapshot",
    section: "planner",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["agent_decisions"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Records the current planner recommendation as an audit row. Does not execute the action.",
  },
  {
    id: "planner_execute",
    method: "POST",
    path: "/admin/planner/execute",
    label: "Conservative planner execute",
    section: "planner",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["agent_decisions"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Runs only the conservative execution envelope. Current allowed actions are D1 reads plus audit insert; no AI, sending, source fetch, or lead insertion.",
  },
  {
    id: "planner_history",
    method: "GET",
    path: "/admin/planner/history?limit=20",
    label: "Recommendation history",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only list of recent planner recommendation audit rows.",
  },
  {
    id: "planner_executions",
    method: "GET",
    path: "/admin/planner/executions?limit=20",
    label: "Execution history",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only list of recent conservative planner execution audit rows.",
  },
  {
    id: "source_list",
    method: "GET",
    path: "/admin/sources?limit=50",
    label: "Sources",
    section: "sources",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists tracked sources and their state.",
  },
  {
    id: "source_add",
    method: "POST",
    path: "/admin/sources",
    label: "Add source",
    section: "sources",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["sources", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Adds a manually chosen source URL for later testing and discovery.",
  },
  {
    id: "source_test",
    method: "POST",
    path: "/admin/sources/:id/test",
    label: "Test source",
    section: "sources",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["sources", "source_runs", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one source URL and records whether it looks useful. Applies failure memory/cooldown policy.",
  },
  {
    id: "source_expand_preview",
    method: "POST",
    path: "/admin/sources/:id/expand-preview",
    label: "Source expand preview",
    section: "sources",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one source page and previews candidate profile/business links. Does not insert leads.",
  },
  {
    id: "source_expand_commit",
    method: "POST",
    path: "/admin/sources/:id/expand-commit",
    label: "Source expand commit",
    section: "sources",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["leads", "lead_discoveries", "source_runs", "sources", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "medium",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed bounded expansion. Can insert deduped leads from a source, but does not call AI or send emails.",
  },
  {
    id: "source_run_tiny",
    method: "POST",
    path: "/admin/sources/run-tiny",
    label: "Run tiny source batch",
    section: "sources",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["sources", "source_runs", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Runs a tiny bounded source test batch. Does not insert leads, call AI, send, or enable the engine.",
  },
  {
    id: "draft_review",
    method: "POST",
    path: "/admin/draft-review/:id",
    label: "Review draft",
    section: "drafts",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["draft_reviews", "strategy_scores", "drafts", "leads", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Records human review decisions so draft quality and strategy scoring can improve.",
  },
  {
    id: "health",
    method: "GET",
    path: "/admin/health",
    label: "Health",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only health report for counters, backlog, flags, and stuck-state detection.",
  },
  {
    id: "diagnostics",
    method: "GET",
    path: "/admin/diagnostics",
    label: "Diagnostics",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only deeper diagnostic report for operational review.",
  },
  {
    id: "tools_capabilities",
    method: "GET",
    path: "/tools/capabilities",
    label: "Public capabilities",
    section: "public",
    safety: "public_read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: false,
    operationsHubRecommended: true,
    description: "Public-safe capability manifest. No admin data or controls.",
  },
];

function groupedRoutes() {
  return routes.reduce<Record<string, RouteCatalogueItem[]>>((acc, route) => {
    acc[route.section] = acc[route.section] || [];
    acc[route.section].push(route);
    return acc;
  }, {});
}

export async function handlePlannerRoutesAdmin(request: Request, env: Env, _pathname: string, json: JsonResponse): Promise<Response> {
  if (request.method === "OPTIONS") return json({ ok: true });
  if (!authorized(request, env)) return json({ ok: false, error: "Unauthorized" }, { status: 401 });
  if (request.method !== "GET") return json({ ok: false, error: "method_not_allowed" }, { status: 405 });

  return json({
    ok: true,
    mode: "planner_route_catalogue",
    contractVersion: "planner_routes_v1",
    generatedAtISO: new Date().toISOString(),
    summary: {
      total: routes.length,
      operatorFacing: routes.filter((route) => route.operatorFacing).length,
      operationsHubRecommended: routes.filter((route) => route.operationsHubRecommended).length,
      confirmRequired: routes.filter((route) => route.requiresConfirm).length,
      networkCalling: routes.filter((route) => route.callsNetwork).length,
      aiCalling: routes.filter((route) => route.callsAI).length,
      emailCapable: routes.filter((route) => route.canSendEmail).length,
    },
    safetyRules: {
      noAdminTokenInWebsiteCode: true,
      preferServerSideProxyForOperationsHub: true,
      requireExplicitConfirmForWriteOrNetworkActions: true,
      aiAndSendingRemainSettingsGated: true,
    },
    integration: {
      recommendedOperationsHubEntry: "/ops/outbound-agent",
      recommendedQuickLinkLabel: "Outbound Agent Cockpit",
      recommendedDefaultView: "/admin/planner/dashboard?compact=1",
      recommendedSelfTestView: "/admin/planner/dashboard/self-test?compact=1",
    },
    groups: groupedRoutes(),
    routes,
  });
}
