import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const plannerRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "planner_report",
    method: "GET",
    path: "/admin/planner",
    label: "Planner report",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Full planner state, safe actions, blocked actions, samples, and recommended next action.",
  }),
  route({
    id: "planner_dashboard",
    method: "GET",
    path: "/admin/planner/dashboard?compact=1",
    label: "Planner dashboard",
    section: "cockpit",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Compact cockpit payload with risk, badges, checklist, counts, latest audit summaries, and refresh hints.",
  }),
  route({
    id: "planner_dashboard_full",
    method: "GET",
    path: "/admin/planner/dashboard",
    label: "Planner dashboard full",
    section: "cockpit",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: false,
    description: "Full cockpit payload including recent events and source runs for deeper investigation.",
  }),
  route({
    id: "planner_dashboard_self_test",
    method: "GET",
    path: "/admin/planner/dashboard/self-test?compact=1",
    label: "Dashboard self-test",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Validates the live dashboard contract for UI readiness without writing anything.",
  }),
  route({
    id: "planner_routes",
    method: "GET",
    path: "/admin/planner/routes",
    label: "Route catalogue",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Self-describing route map for UI, API, CLI, and chat-agent clients.",
  }),
  route({
    id: "zero_source_route_map",
    method: "GET",
    path: "/admin/planner/routes",
    label: "Zero-source route map",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only route-map guidance for starting with no supplied source list: read autonomy settings, bootstrap source-expansion seeds, run tiny bounded candidate-memory scans, rotate through sitemap/public-link/query-hint recovery when thin, review candidates before source promotion, and run opportunity discovery only after live source memory exists.",
  }),
  route({
    id: "growth_overview",
    method: "GET",
    path: "/admin/growth/overview",
    label: "Growth overview",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Reads Growth Autonomy goals, channels, counts, and budget state. It is a visibility route only and cannot execute growth actions.",
  }),
  route({
    id: "growth_brief",
    method: "GET",
    path: "/admin/growth/brief?profile=free_safe",
    label: "Growth daily brief",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: ["growth_budget_ledger"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Reads the canonical Growth brief for budget posture, signal summary, action summary, latest audit events, and suggested operator focus. It does not generate drafts or perform external actions.",
  }),
  route({
    id: "growth_strategy",
    method: "GET",
    path: "/admin/growth/strategy?limit=25",
    label: "Growth strategy goals",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists saved Growth Strategy Board goals that guide EVAVO service focus, audience focus, region focus, budget profile, and automation mode.",
  }),
  route({
    id: "growth_strategy_save",
    method: "POST",
    path: "/admin/growth/strategy?confirm=1",
    label: "Save growth strategy goal",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_goals"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirm-saves Growth Strategy Board goal metadata only. It cannot run discovery, generate drafts, execute actions, or contact anyone.",
  }),
  route({
    id: "growth_channels",
    method: "GET",
    path: "/admin/growth/channels?limit=50",
    label: "Growth channels",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists channel-rule memory for owned channels, provider-expected spaces, direct contact routes, community channels, procurement channels, and blocked channels.",
  }),
  route({
    id: "growth_channels_save",
    method: "POST",
    path: "/admin/growth/channels?confirm=1",
    label: "Save growth channel rule",
    section: "growth",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["growth_channels"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirm-saves Growth channel/rule metadata only. It cannot perform outreach, posting, form submission, or other external actions.",
  }),
  route({
    id: "growth_signals",
    method: "GET",
    path: "/admin/growth/signals?limit=50",
    label: "Growth signals",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists saved Growth signals for future discovery and engagement planning. Read-only; it does not fetch, draft, or execute anything.",
  }),
  route({
    id: "growth_actions",
    method: "GET",
    path: "/admin/growth/actions?limit=50",
    label: "Growth actions",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists queued Growth action records for the future engagement queue. Read-only; it cannot approve, post, send, or submit actions.",
  }),
  route({
    id: "growth_budget",
    method: "GET",
    path: "/admin/growth/budget?profile=free_safe",
    label: "Growth budget ledger",
    section: "growth",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: ["growth_budget_ledger"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Reads or initializes today's Growth budget ledger for visibility. It records budget state only and does not run discovery or external actions.",
  }),
  route({
    id: "planner_record",
    method: "POST",
    path: "/admin/planner/record",
    label: "Record planner snapshot",
    section: "planner",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["agent_decisions"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Records the current planner recommendation as an audit row. Does not execute the action.",
  }),
  route({
    id: "planner_execute",
    method: "POST",
    path: "/admin/planner/execute",
    label: "Conservative planner execute",
    section: "planner",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["agent_decisions"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Runs only the conservative execution envelope. No paid AI, sending, or uncontrolled source expansion.",
  }),
  route({
    id: "planner_history",
    method: "GET",
    path: "/admin/planner/history?limit=20",
    label: "Recommendation history",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only list of recent planner recommendation audit rows.",
  }),
  route({
    id: "planner_executions",
    method: "GET",
    path: "/admin/planner/executions?limit=20",
    label: "Execution history",
    section: "planner",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only list of recent conservative planner execution audit rows.",
  }),
  route({
    id: "autonomy_settings",
    method: "GET",
    path: "/admin/settings/autonomy",
    label: "Autonomy settings",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Reads the current autonomy mode, toggles, caps, and resolved policy used by scheduled and manual runs.",
  }),
  route({
    id: "autonomy_settings_save",
    method: "POST",
    path: "/admin/settings/autonomy",
    label: "Save autonomy settings",
    section: "safety",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["settings"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Saves autonomy mode, free-safe toggles, and caps. Does not run discovery, AI, or sending by itself.",
  }),
];
