import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const safetyRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "draft_review",
    method: "POST",
    path: "/admin/draft-review/:id",
    label: "Review draft",
    section: "drafts",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["draft_reviews", "strategy_scores", "drafts", "leads", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Records human review decisions so draft quality and strategy scoring can improve.",
  }),
  route({
    id: "health",
    method: "GET",
    path: "/admin/health",
    label: "Health",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only health report for counters, backlog, flags, and stuck-state detection.",
  }),
  route({
    id: "diagnostics",
    method: "GET",
    path: "/admin/diagnostics",
    label: "Diagnostics",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only deeper diagnostic report for operational review.",
  }),
  route({
    id: "schema",
    method: "GET",
    path: "/admin/schema",
    label: "Schema",
    section: "safety",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only schema/check contract for admin diagnostics.",
  }),
  route({
    id: "tools_capabilities",
    method: "GET",
    path: "/tools/capabilities",
    label: "Public capabilities",
    section: "public",
    safety: "public_read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: false,
    operationsHubRecommended: true,
    description: "Public-safe capability manifest. No admin data or controls.",
  }),
];
