import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const opportunityRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "opportunity_summary",
    method: "GET",
    path: "/admin/opportunities/summary",
    label: "Opportunity summary",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only summary of opportunity sources, saved opportunities, types, and top review items.",
  }),
  route({
    id: "opportunity_learning",
    method: "GET",
    path: "/admin/opportunities/learning",
    label: "Opportunity learning",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only review history, decision counts, and opportunity strategy scores.",
  }),
  route({
    id: "opportunity_list",
    method: "GET",
    path: "/admin/opportunities?limit=50",
    label: "Opportunities",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists saved opportunities waiting for review, watching, shortlist, or archive decisions.",
  }),
  route({
    id: "opportunity_source_list",
    method: "GET",
    path: "/admin/opportunities/sources?limit=50",
    label: "Opportunity sources",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists tracked grant, tender, funding, partner, supplier, and contract-signal sources.",
  }),
  route({
    id: "opportunity_source_add",
    method: "POST",
    path: "/admin/opportunities/sources",
    label: "Add opportunity source",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["opportunity_sources"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Adds a manually selected opportunity source for later testing and preview.",
  }),
  route({
    id: "opportunity_source_test",
    method: "POST",
    path: "/admin/opportunities/sources/:id/test",
    label: "Test opportunity source",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["opportunity_sources"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one opportunity source and records source health plus candidate count. Does not save opportunities.",
  }),
  route({
    id: "opportunity_source_preview",
    method: "POST",
    path: "/admin/opportunities/sources/:id/preview?limit=50",
    label: "Preview opportunity source",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one opportunity source and previews scored candidates. Does not save opportunities.",
  }),
  route({
    id: "opportunity_commit_preview",
    method: "POST",
    path: "/admin/opportunities/sources/:id/commit-preview",
    label: "Save previewed opportunities",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["opportunities"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed save step. Re-runs preview, dedupes, and saves high-score candidates as review items only.",
  }),
  route({
    id: "opportunity_run_due",
    method: "POST",
    path: "/admin/opportunities/run-due",
    label: "Run due opportunities",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["opportunity_sources", "opportunities", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed free-safe manual run for due opportunity sources. Saves high-score review items only; no AI, sending, posting, or applying.",
  }),
  route({
    id: "opportunity_review",
    method: "POST",
    path: "/admin/opportunities/:id/review",
    label: "Review opportunity",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["opportunity_reviews", "opportunity_strategy_scores", "opportunities"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Records a review decision and updates learning scores so future ranking can improve.",
  }),
  route({
    id: "opportunity_reviews",
    method: "GET",
    path: "/admin/opportunities/reviews?limit=50",
    label: "Opportunity reviews",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists recent opportunity review decisions.",
  }),
  route({
    id: "opportunity_strategy_scores",
    method: "GET",
    path: "/admin/opportunities/strategy-scores?limit=50",
    label: "Opportunity strategy scores",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists learned score adjustments by opportunity type and category.",
  }),
];
