import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const opportunityRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "opportunity_summary",
    method: "GET",
    path: "/admin/opportunities/summary",
    label: "Opportunity summary",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only summary of opportunity sources, saved opportunities, types, and top review items.",
  }),
  route({
    id: "opportunity_learning",
    method: "GET",
    path: "/admin/opportunities/learning",
    label: "Opportunity learning",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only review history, decision counts, and opportunity strategy scores.",
  }),
  route({
    id: "opportunity_scoring_diagnostics",
    method: "GET",
    path: "/admin/opportunities/scoring-diagnostics?limit=100",
    label: "Opportunity scoring diagnostics",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only calibration diagnostics for boosted/penalised opportunities, reason counts, source-health impact, review-learning impact, and raw-vs-calibrated score spread.",
  }),
  route({
    id: "opportunity_runs",
    method: "GET",
    path: "/admin/opportunities/runs?limit=25",
    label: "Opportunity run audit",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists recent scheduled/manual opportunity discovery runs with status, counts, and failure summary.",
  }),
  route({
    id: "opportunity_run_detail",
    method: "GET",
    path: "/admin/opportunities/runs/:id",
    label: "Opportunity run detail",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Reads one opportunity run with source-level audit rows and candidate rejection rows.",
  }),
  route({
    id: "opportunity_source_health",
    method: "GET",
    path: "/admin/opportunities/sources/health?limit=50",
    label: "Opportunity source health",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Scores opportunity sources using run audit data, saved/rejected/duplicate rates, failures, and recommended source-quality actions.",
  }),
  route({
    id: "opportunity_source_health_action",
    method: "POST",
    path: "/admin/opportunities/sources/:id/health-action",
    label: "Opportunity source health action",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["opportunity_sources", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed local metadata action for source quality: pause, activate, lower priority, raise priority, or reset source error state. No AI, email, network, posting, or external action.",
  }),
  route({
    id: "source_expansion_bootstrap",
    method: "POST",
    path: "/admin/opportunities/sources/expansion/bootstrap",
    label: "Bootstrap source expansion seeds",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["source_expansion_seeds", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed local bootstrap of durable source-expansion seeds. No network, AI, email, or external action.",
  }),
  route({
    id: "source_expansion_scan",
    method: "POST",
    path: "/admin/opportunities/sources/expansion/scan",
    label: "Bounded source expansion scan",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["source_expansion_runs", "source_expansion_attempts", "source_expansion_candidates", "source_expansion_seeds", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed bounded scan of due source-expansion seeds. Stores candidate-source memory only; saving to opportunity_sources still requires separate confirmation.",
  }),
  route({
    id: "source_expansion_sitemap_scan",
    method: "POST",
    path: "/admin/opportunities/sources/expansion/sitemap-scan",
    label: "Bounded sitemap source expansion scan",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["source_expansion_candidates", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed bounded robots/sitemap discovery from known source domains. Stores candidate-source memory only; saving to opportunity_sources still requires separate confirmation.",
  }),
  route({
    id: "source_expansion_public_link_scan",
    method: "POST",
    path: "/admin/opportunities/sources/expansion/public-directory-scan",
    label: "Public link graph source scan",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["source_expansion_candidates", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed bounded scan of ordinary public links from known source pages. Looks for partner, client, supplier, funding, portfolio, and opportunity-style source candidates. Stores candidate-source memory only; saving to opportunity_sources still requires separate confirmation.",
  }),
  route({
    id: "source_expansion_candidates",
    method: "GET",
    path: "/admin/opportunities/sources/expansion/candidates?status=candidate&limit=50",
    label: "Source expansion candidates",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only list of source candidates learned by the continuous expansion engine, sitemap discovery, public-link graph discovery, and query-hint resolving.",
  }),
  route({
    id: "source_expansion_learn",
    method: "POST",
    path: "/admin/opportunities/sources/expansion/learn",
    label: "Learn source expansion quality",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["source_expansion_strategy_scores", "source_expansion_seeds", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed local learning pass that scores expansion strategies from candidates, saved sources, saved-source origins, source outcomes, public-link graph yield, and opportunity yield.",
  }),
  route({
    id: "source_expansion_strategies",
    method: "GET",
    path: "/admin/opportunities/sources/expansion/strategies?limit=50",
    label: "Source expansion strategy scores",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only strategy-quality scores and recommendations for continuous source expansion, sitemap discovery, public-link graph discovery, and query-hint resolving.",
  }),
  route({
    id: "source_expansion_budget_recommendations",
    method: "GET",
    path: "/admin/opportunities/sources/expansion/budget-recommendations",
    label: "Source expansion budget recommendations",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Read-only adaptive recommendation layer for query hints, public-link graph discovery, sitemap scans, bounded expansion, and source-candidate preview attention.",
  }),
  route({
    id: "opportunity_list",
    method: "GET",
    path: "/admin/opportunities?limit=50",
    label: "Opportunities",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists saved opportunities waiting for review, watching, shortlist, or archive decisions.",
  }),
  route({
    id: "opportunity_source_list",
    method: "GET",
    path: "/admin/opportunities/sources?limit=50&origin=public_link_graph",
    label: "Opportunity sources",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists tracked grant, tender, funding, partner, supplier, and contract-signal sources. Supports read-only source-origin filtering with origin=query_hint, public_link_graph, sitemap, source_expansion, source_candidate_preview, other_saved_candidate, manual_or_unknown, and legacy candidate_preview.",
  }),
  route({
    id: "opportunity_source_candidate_preview",
    method: "GET",
    path: "/admin/opportunities/sources/candidates/preview?limit=50",
    label: "Opportunity source candidate preview",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Preview-only deterministic source-candidate discovery. Scores likely grant, tender, procurement, creative funding, and digital-service sources; dedupes against existing opportunity_sources; saves nothing.",
  }),
  route({
    id: "opportunity_source_candidate_commit",
    method: "POST",
    path: "/admin/opportunities/sources/candidates/commit",
    label: "Save source candidates",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["opportunity_sources", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed local metadata save for selected previewed source candidates. Rebuilds the server-side candidate set, dedupes by domain, inserts into opportunity_sources, logs an event, and does not call network, AI, or email.",
  }),
  route({
    id: "opportunity_source_add",
    method: "POST",
    path: "/admin/opportunities/sources",
    label: "Add opportunity source",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["opportunity_sources"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Adds a manually selected opportunity source for later testing and preview.",
  }),
  route({
    id: "opportunity_source_test",
    method: "POST",
    path: "/admin/opportunities/sources/:id/test",
    label: "Test opportunity source",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["opportunity_sources"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one opportunity source and records source health plus candidate count. Does not save opportunities.",
  }),
  route({
    id: "opportunity_source_preview",
    method: "POST",
    path: "/admin/opportunities/sources/:id/preview?limit=50",
    label: "Preview opportunity source",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one opportunity source and previews scored candidates. Does not save opportunities.",
  }),
  route({
    id: "opportunity_commit_preview",
    method: "POST",
    path: "/admin/opportunities/sources/:id/commit-preview",
    label: "Save previewed opportunities",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["opportunities"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed save step. Re-runs preview, dedupes, and saves high-score candidates as review items only.",
  }),
  route({
    id: "opportunity_run_due",
    method: "POST",
    path: "/admin/opportunities/run-due",
    label: "Run due opportunities",
    section: "opportunities",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["opportunity_sources", "opportunities", "events", "opportunity_runs", "opportunity_run_source_results", "opportunity_candidate_rejections"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed free-safe manual run for due opportunity sources. Saves high-score review items only and records a run audit trail; no AI, sending, posting, or applying.",
  }),
  route({
    id: "opportunity_review",
    method: "POST",
    path: "/admin/opportunities/:id/review",
    label: "Review opportunity",
    section: "opportunities",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["opportunity_reviews", "opportunity_strategy_scores", "opportunities"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Records a review decision and updates learning scores so future ranking can improve.",
  }),
  route({
    id: "opportunity_reviews",
    method: "GET",
    path: "/admin/opportunities/reviews?limit=50",
    label: "Opportunity reviews",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists recent opportunity review decisions.",
  }),
  route({
    id: "opportunity_strategy_scores",
    method: "GET",
    path: "/admin/opportunities/strategy-scores?limit=50",
    label: "Opportunity strategy scores",
    section: "opportunities",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists learned score adjustments by opportunity type and category.",
  }),
];
