import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const plannerRouteCatalogue: RouteCatalogueItem[] = [
  route({ id: "planner_report", method: "GET", path: "/admin/planner", label: "Planner report", section: "planner", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Full planner state, safe actions, blocked actions, samples, and recommended next action." }),
  route({ id: "planner_dashboard", method: "GET", path: "/admin/planner/dashboard?compact=1", label: "Planner dashboard", section: "cockpit", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Compact cockpit payload with risk, badges, checklist, counts, latest audit summaries, and refresh hints." }),
  route({ id: "planner_dashboard_full", method: "GET", path: "/admin/planner/dashboard", label: "Planner dashboard full", section: "cockpit", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: false, description: "Full cockpit payload including recent events and source runs for deeper investigation." }),
  route({ id: "planner_dashboard_self_test", method: "GET", path: "/admin/planner/dashboard/self-test?compact=1", label: "Dashboard self-test", section: "safety", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Validates the live dashboard contract for UI readiness without writing anything." }),
  route({ id: "planner_routes", method: "GET", path: "/admin/planner/routes", label: "Route catalogue", section: "planner", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Self-describing route map for UI, API, CLI, and chat-agent clients." }),
  route({ id: "zero_source_route_map", method: "GET", path: "/admin/planner/routes", label: "Zero-source route map", section: "planner", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Read-only route-map guidance for starting with no supplied source list and routing through approved source-recovery checks before discovery." }),

  route({ id: "growth_overview", method: "GET", path: "/admin/growth/overview", label: "Growth overview", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Reads Growth Autonomy goals, channels, counts, and budget state. It is a visibility route only." }),
  route({ id: "growth_brief", method: "GET", path: "/admin/growth/brief?profile=free_safe", label: "Growth daily brief", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: ["growth_budget_ledger"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Reads the canonical Growth brief for budget posture, signal summary, action summary, recent audit events, and suggested operator focus." }),
  route({ id: "growth_capabilities", method: "GET", path: "/admin/growth/capabilities", label: "Growth capabilities", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Reads the Growth Operator capability registry and autonomy levels. It is a registry route only." }),
  route({ id: "growth_operator", method: "GET", path: "/admin/growth/operator", label: "Growth operator intelligence", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Reads campaign intelligence overview including campaigns, experiments, and recent reasoned decisions." }),
  route({ id: "growth_campaigns", method: "GET", path: "/admin/growth/campaigns?limit=25", label: "Growth campaigns", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists Growth campaign records for the operator brain." }),
  route({ id: "growth_campaign_save", method: "POST", path: "/admin/growth/campaigns?confirm=1", label: "Save growth campaign", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_campaigns"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-saves Growth campaign metadata only." }),
  route({ id: "growth_experiments", method: "GET", path: "/admin/growth/experiments?limit=25", label: "Growth experiments", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists Growth experiment records for campaign testing and learning." }),
  route({ id: "growth_experiment_save", method: "POST", path: "/admin/growth/experiments?confirm=1", label: "Save growth experiment", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_experiments"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-saves Growth experiment metadata only." }),
  route({ id: "growth_decisions", method: "GET", path: "/admin/growth/decisions?limit=25", label: "Growth decisions", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists reasoned Growth campaign decision records." }),
  route({ id: "growth_decision_plan", method: "POST", path: "/admin/growth/decisions/plan?confirm=1", label: "Plan growth decision", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_decisions", "growth_candidate_actions"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-plans a deterministic next-best campaign decision and candidate action set." }),
  route({ id: "growth_strategy", method: "GET", path: "/admin/growth/strategy?limit=25", label: "Growth strategy goals", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists saved Growth Strategy Board goals." }),
  route({ id: "growth_strategy_save", method: "POST", path: "/admin/growth/strategy?confirm=1", label: "Save growth strategy goal", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_goals", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-saves Growth Strategy Board goal metadata and an audit row." }),
  route({ id: "growth_channels", method: "GET", path: "/admin/growth/channels?limit=50", label: "Growth channels", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists Growth channel-rule memory." }),
  route({ id: "growth_channels_save", method: "POST", path: "/admin/growth/channels?confirm=1", label: "Save growth channel rule", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_channels", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-saves Growth channel/rule metadata and an audit row." }),

  route({ id: "growth_signals", method: "GET", path: "/admin/growth/signals?limit=50", label: "Growth signals", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists saved Growth signals for planning and review." }),
  route({ id: "growth_signal_save", method: "POST", path: "/admin/growth/signals?confirm=1", label: "Save growth signal", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_signals", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-saves one Growth signal metadata record and an audit row." }),
  route({ id: "growth_signal_status", method: "POST", path: "/admin/growth/signals/status?confirm=1", label: "Review growth signal status", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_signals", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-updates Growth signal review status metadata and records the decision in audit." }),

  route({ id: "growth_actions", method: "GET", path: "/admin/growth/actions?limit=50", label: "Growth actions", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists queued Growth action records for review." }),
  route({ id: "growth_action_save", method: "POST", path: "/admin/growth/actions?confirm=1", label: "Save growth action", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_actions", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-saves one Growth action queue metadata record and an audit row." }),
  route({ id: "growth_action_plan", method: "POST", path: "/admin/growth/actions/plan?confirm=1", label: "Plan growth action", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_actions", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-plans one deterministic queue record from a saved signal. No AI or network call is made." }),
  route({ id: "growth_action_status", method: "POST", path: "/admin/growth/actions/status?confirm=1", label: "Review growth action status", section: "growth", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["growth_actions", "growth_audit_events"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Confirm-updates Growth action review status metadata and records the decision in audit." }),

  route({ id: "growth_audit", method: "GET", path: "/admin/growth/audit?limit=50", label: "Growth audit events", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Lists recent Growth audit events for explainability across strategy, channel, signal, action, planning, and review metadata." }),
  route({ id: "growth_budget", method: "GET", path: "/admin/growth/budget?profile=free_safe", label: "Growth budget ledger", section: "growth", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: ["growth_budget_ledger"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Reads or initializes today's Growth budget ledger for visibility." }),

  route({ id: "planner_record", method: "POST", path: "/admin/planner/record", label: "Record planner snapshot", section: "planner", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["agent_decisions"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Records the current planner recommendation as an audit row." }),
  route({ id: "planner_execute", method: "POST", path: "/admin/planner/execute", label: "Conservative planner execute", section: "planner", safety: "confirm_required", readOnly: false, requiresConfirm: true, writesTables: ["agent_decisions"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Runs only the conservative execution envelope. No paid AI, sending, or uncontrolled source expansion." }),
  route({ id: "planner_history", method: "GET", path: "/admin/planner/history?limit=20", label: "Recommendation history", section: "planner", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Read-only list of recent planner recommendation audit rows." }),
  route({ id: "planner_executions", method: "GET", path: "/admin/planner/executions?limit=20", label: "Execution history", section: "planner", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Read-only list of recent conservative planner execution audit rows." }),
  route({ id: "autonomy_settings", method: "GET", path: "/admin/settings/autonomy", label: "Autonomy settings", section: "safety", safety: "read_only", readOnly: true, requiresConfirm: false, writesTables: [], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Reads the current autonomy mode, toggles, caps, and resolved policy used by scheduled and manual runs." }),
  route({ id: "autonomy_settings_save", method: "POST", path: "/admin/settings/autonomy", label: "Save autonomy settings", section: "safety", safety: "settings_gated", readOnly: false, requiresConfirm: false, writesTables: ["settings"], callsNetwork: false, callsAI: false, canSendEmail: false, costRisk: "none", operatorFacing: true, operationsHubRecommended: true, description: "Saves autonomy mode, free-safe toggles, and caps. Does not run discovery, AI, or sending by itself." }),
];
