import { RouteCatalogueItem, route } from "./routeCatalogueTypes";

export const sourceRouteCatalogue: RouteCatalogueItem[] = [
  route({
    id: "source_list",
    method: "GET",
    path: "/admin/sources?limit=50",
    label: "Sources",
    section: "sources",
    safety: "read_only",
    readOnly: true,
    requiresConfirm: false,
    writesTables: [],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Lists tracked sources and their state.",
  }),
  route({
    id: "source_add",
    method: "POST",
    path: "/admin/sources",
    label: "Add source",
    section: "sources",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["sources", "events"],
    callsNetwork: false,
    callsAI: false,
    canSendEmail: false,
    costRisk: "none",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Adds a manually chosen source URL for later testing and discovery.",
  }),
  route({
    id: "source_test",
    method: "POST",
    path: "/admin/sources/:id/test",
    label: "Test source",
    section: "sources",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["sources", "source_runs", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one source URL and records whether it looks useful. Applies failure memory and cooldown policy.",
  }),
  route({
    id: "source_expand_preview",
    method: "POST",
    path: "/admin/sources/:id/expand-preview",
    label: "Source expand preview",
    section: "sources",
    safety: "settings_gated",
    readOnly: false,
    requiresConfirm: false,
    writesTables: ["events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Fetches one source page and previews candidate profile or business links. Does not insert leads.",
  }),
  route({
    id: "source_expand_commit",
    method: "POST",
    path: "/admin/sources/:id/expand-commit",
    label: "Source expand commit",
    section: "sources",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["leads", "lead_discoveries", "source_runs", "sources", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "medium",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Confirmed bounded expansion. Can insert deduped leads from a source, but does not call AI or send emails.",
  }),
  route({
    id: "source_run_tiny",
    method: "POST",
    path: "/admin/sources/run-tiny",
    label: "Run tiny source batch",
    section: "sources",
    safety: "confirm_required",
    readOnly: false,
    requiresConfirm: true,
    writesTables: ["sources", "source_runs", "events"],
    callsNetwork: true,
    callsAI: false,
    canSendEmail: false,
    costRisk: "low",
    operatorFacing: true,
    operationsHubRecommended: true,
    description: "Runs a tiny bounded source test batch. Does not insert leads, call AI, send, or enable the engine.",
  }),
];
