create table if not exists growth_autonomy_usage_windows (
  organisation_id text not null,
  workspace_id text not null,
  window_key text not null,
  profile text not null,
  max_runs_per_day integer not null,
  runs_started integer not null default 0,
  reports_generated integer not null default 0,
  sources_visited integer not null default 0,
  network_requests integer not null default 0,
  candidates_created integer not null default 0,
  cpu_milliseconds integer not null default 0,
  d1_rows_read integer not null default 0,
  d1_rows_written integer not null default 0,
  storage_bytes integer not null default 0,
  estimated_paid_spend_cents integer not null default 0,
  last_reservation_id text not null,
  created_at text not null,
  updated_at text not null,
  primary key (organisation_id, workspace_id, window_key),
  check (profile in ('paused', 'light', 'balanced', 'high')),
  check (max_runs_per_day between 1 and 6),
  check (runs_started >= 0),
  check (reports_generated >= 0),
  check (sources_visited >= 0),
  check (network_requests >= 0),
  check (candidates_created >= 0),
  check (cpu_milliseconds >= 0),
  check (d1_rows_read >= 0),
  check (d1_rows_written >= 0),
  check (storage_bytes >= 0),
  check (estimated_paid_spend_cents = 0),
  check (window_key glob '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  check (last_reservation_id glob 'growth-run:*'),
  check (created_at glob '*Z'),
  check (updated_at glob '*Z')
);

create table if not exists growth_autonomy_run_reservations (
  reservation_id text primary key,
  run_id text not null unique,
  organisation_id text not null,
  workspace_id text not null,
  window_key text not null,
  profile text not null,
  state text not null default 'active',
  max_sources_per_run integer not null,
  max_network_requests_per_run integer not null,
  max_candidates_per_run integer not null,
  max_reports_per_run integer not null,
  max_cpu_milliseconds_per_run integer not null,
  max_d1_rows_read_per_run integer not null,
  max_d1_rows_written_per_run integer not null,
  max_storage_bytes_per_run integer not null,
  sources_visited integer not null default 0,
  network_requests integer not null default 0,
  candidates_created integer not null default 0,
  reports_generated integer not null default 0,
  cpu_milliseconds integer not null default 0,
  d1_rows_read integer not null default 0,
  d1_rows_written integer not null default 0,
  storage_bytes integer not null default 0,
  reserved_at text not null,
  expires_at text not null,
  completed_at text,
  usage_applied integer not null default 0,
  check (reservation_id glob 'growth-run:*'),
  check (profile in ('paused', 'light', 'balanced', 'high')),
  check (state in ('active', 'completed', 'failed')),
  check (max_sources_per_run between 1 and 32),
  check (max_network_requests_per_run between 1 and 96),
  check (max_candidates_per_run between 1 and 16),
  check (max_reports_per_run between 1 and 3),
  check (max_cpu_milliseconds_per_run between 1 and 5000),
  check (max_d1_rows_read_per_run between 2 and 3000),
  check (max_d1_rows_written_per_run between 5 and 150),
  check (max_storage_bytes_per_run between 1 and 3000000),
  check (sources_visited between 0 and max_sources_per_run),
  check (network_requests between 0 and max_network_requests_per_run),
  check (candidates_created between 0 and max_candidates_per_run),
  check (reports_generated between 0 and max_reports_per_run),
  check (cpu_milliseconds between 0 and max_cpu_milliseconds_per_run),
  check (d1_rows_read between 0 and max_d1_rows_read_per_run),
  check (d1_rows_written between 0 and max_d1_rows_written_per_run),
  check (storage_bytes between 0 and max_storage_bytes_per_run),
  check (reserved_at glob '*Z'),
  check (expires_at glob '*Z'),
  check (completed_at is null or completed_at glob '*Z'),
  check (usage_applied in (0, 1)),
  foreign key (organisation_id, workspace_id, window_key)
    references growth_autonomy_usage_windows (organisation_id, workspace_id, window_key)
);

create index if not exists growth_autonomy_usage_window_updated_idx
  on growth_autonomy_usage_windows (updated_at desc);

create index if not exists growth_autonomy_run_tenant_window_idx
  on growth_autonomy_run_reservations (
    organisation_id,
    workspace_id,
    window_key,
    reserved_at desc
  );

create index if not exists growth_autonomy_run_state_expiry_idx
  on growth_autonomy_run_reservations (state, expires_at);
